source 'https://rubygems.org'

#if ENV.key?('PUPPET_VERSION')
  #puppetversion = "= #{ENV['PUPPET_VERSION']}"
#else
  #puppetversion = ['>= 3.8']
#end

gem 'rspec-puppet', :require => false
gem 'puppetlabs_spec_helper',  :require => false
gem 'puppet'
gem 'rake'
gem 'metadata-json-lint'
gem 'puppet-lint', '>= 1.0.0'
gem 'facter', '>= 1.7.0'
gem 'rspec-puppet-facts'
gem 'hiera-puppet-helper'

#gem 'rake'
#gem 'puppet-lint'
#gem 'rspec-puppet'
#gem 'puppetlabs_spec_helper'
#gem 'puppet', '3.8.1'

# rspec must be v2 for ruby 1.8.7
if RUBY_VERSION >= '1.8.7' and RUBY_VERSION < '1.9'
  gem 'rspec', '~> 2.0'
end

