# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puppetlabs/ubuntu-12.04-64-puppet"

  config.vm.provision :hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "puppet" do |puppet|
    puppet.vm.network :private_network, ip: "192.168.11.3"
    puppet.vm.hostname = "puppet"

    puppet.vm.synced_folder "../../", "/openstack"

    puppet.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] =  "1024"
        v.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.vm.define "control" do |control|
    control.vm.network :private_network, ip: "192.168.11.4"
    control.vm.hostname = "control"

    control.vm.synced_folder "../../", "/openstack"

    control.vm.provider "vmware_fusion" do |v|
        v.vmx["numvcpus"] = "1"
        v.vmx["memsize"] =  "4048"
        v.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.vm.define "control2" do |control2|
    control2.vm.network :private_network, ip: "192.168.11.5"
    control2.vm.hostname = "control2"

    control2.vm.synced_folder "../../", "/openstack"

    control2.vm.provider "vmware_fusion" do |v|
        v.vmx["numvcpus"] = "1"
        v.vmx["memsize"] =  "4048"
        v.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.vm.define "control3" do |control3|
    control3.vm.network :private_network, ip: "192.168.11.6"
    control3.vm.hostname = "control3"

    control3.vm.synced_folder "../../", "/openstack"

    control3.vm.provider "vmware_fusion" do |v|
        v.vmx["numvcpus"] = "1"
        v.vmx["memsize"] =  "4048"
        v.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.vm.define "compute" do |compute|
    compute.vm.network :private_network, ip: "192.168.11.7"
    compute.vm.hostname = "compute"

    compute.vm.synced_folder "../../", "/openstack"

    compute.vm.provider "vmware_fusion" do |v|
        v.vmx["numvcpus"] = "2"
        v.vmx["memsize"] =  "2048"
        v.vmx["vhv.enable"] = "TRUE"
    end
  end

#  config.vm.define "tempest" do |tempest|
#    tempest.vm.network :private_network, ip: "192.168.11.11"
#    tempest.vm.network :private_network, ip: "192.168.22.11"
#    tempest.vm.network :private_network, ip: "172.16.33.11"
#    tempest.vm.network :private_network, ip: "172.16.44.11"
#
#    tempest.vm.hostname = "tempest"
#
#    tempest.vm.synced_folder "../../", "/openstack"
#
#    tempest.vm.provider "vmware_fusion" do |v|
#      v.vmx["memsize"] = "512"
#      v.vmx["vhv.enable"] = "TRUE"
#    end
#  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file base.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  # config.vm.provision :puppet do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "site.pp"
  # end

end
